### ISSUE TITLE
How to get predicted trajectory?

### ISSUE THREAD

**Issue by Psychic-DL** [davidglavas/sgan-experiments#1]
Hello,Is there any simple way to save the predicted trajectory (e.g., x-y coordinates) in a txt or any file format?Thx. @davidglavas

**Comment by davidglavas** [comment]
Yes ofc, you could for example use the existing evaluation script and write the predicted trajectories https://github.com/davidglavas/sgan-experiments/blob/b1f53440dcb014e8b971a1406ce14ac216a7b512/scripts/evaluate_model.py#L133 into a file.

**Comment by Psychic-DL** [comment]
Thanks for your reply!I ran the evaluation script to evaluate the pre-training model published by the original author and saved the prediction results.The result under biwi_eth.txt(has 5492 lines) is as follows（only has 80 lines）, could you help me explain this result?Thank you very much!
![image](https://user-images.githubusercontent.com/30741409/67484115-f4436f00-f699-11e9-8d46-098c0e06f516.png)
